### ISSUE TITLE
Reference Part

### ISSUE THREAD

**Issue by tonysy** [lupantech/MathVista#1]
Hi,

Thanks for the great works, impressive.
We are glad to see the MMBench has been mentioned in this work, while the information about MMBench is missing in the reference part. If possible, please update the reference part, thanks.
![image](https://github.com/lupantech/MathVista/assets/7881589/2d35448a-6891-45de-8da0-3fcfd68eb265)

Also, welcome to contribute the MathVista into OpenCompass for more visibility.
https://github.com/open-compass/OpenCompass/

**Comment by lupantech** [comment]
Hi Songyang,

Thank you for pointing out the missing reference in our paper. We have fixed the paper. 

We appreciate your suggestion and will contribute our dataset to OpenCompass.

Best regards,
Pan
