### ISSUE TITLE
What was the intention of `image_path` in the model files such as gpt.py?

### ISSUE THREAD

**Issue by mattmazzola** [lupantech/MathVista#18]
The `get_response` function takes `image_path` but the variable is unused.

I assumed it would be useful if targeting another LMM like GPT4V; however, the code to set the image path as a user message is not there so I wanted to confirm.

What was the intention of the image_path variable in the models?

I see the `image_path` is actually used for `Bard`, 

https://github.com/lupantech/MathVista/blob/82f68d09b4cbffe9d0dfd7542c599810e30c9a99/models/bard.py#L28-L36

but not used for `Claude` or `GPT`
Is this an oversight and it should be used or was this intentional simply to keep the signature of functions the same?

https://github.com/lupantech/MathVista/blob/82f68d09b4cbffe9d0dfd7542c599810e30c9a99/models/claude.py#L17-L39

https://github.com/lupantech/MathVista/blob/82f68d09b4cbffe9d0dfd7542c599810e30c9a99/models/gpt.py#L16-L40

**Comment by lupantech** [comment]
Thank you for pointing it out! The `image_path` variable was intentionally included to maintain consistency in the function signatures across different models.
