### ISSUE TITLE
Problem 272: Mismatch between answer choices in the problem and answer choices in the query 

### ISSUE THREAD

**Issue by mbchang** [lupantech/MathVista#2]
Unless I am mistaken, it appears that at least for one problem there is a potential mismatch between the answer choices in the problem dict (the entries inside [testmini.json](https://github.com/lupantech/MathVista/blob/main/data/testmini.json) and the answer choices inside query prompt (the entries inside [query.json](https://github.com/lupantech/MathVista/blob/main/data/query.json)).

The problems are the following:
1. The **content** of the answer choices in the problem dict do not match the content of the answer choices in the query prompt.
2. The **ordering** of the answer choices in the problem dict do not match the content of the answer choices in the query prompt.

Consider the following example, which is example number 272.
<img width="352" alt="image" src="https://github.com/lupantech/MathVista/assets/6439365/afe92525-0032-494c-b333-3cc2b744be5a">
In `testmini.json`, the problem dict is the following:
```
"272": {
    "question": "What time does the clock show?",
    "image": "images/272.jpg",
    "choices": [
        "9:30",
        "1:30",
        "4:30",
        "5:30",
        "11:30"
    ],
    "unit": null,
    "precision": null,
    "answer": "4:30",
    "question_type": "multi_choice",
    "answer_type": "text",
    "pid": "272",
    "metadata": {
        "split": "testmini",
        "language": "english",
        "img_width": 261,
        "img_height": 261,
        "source": "IconQA",
        "category": "math-targeted-vqa",
        "task": "math word problem",
        "context": "abstract scene",
        "grade": "elementary school",
        "skills": [
            "numeric commonsense"
        ]
    }
},
```
However, in `query.json`, the prompt is the following: 
```
"272": "Hint: Please answer the question and provide the correct option letter, e.g., A, B, C, D, at the end.
Question: What time does the clock show?
Choices:
(A) 1:30
(B) 6:30
(C) 5:30
(D) 4:30
(E) 12:30",
```
We can see in [this line](https://github.com/lupantech/MathVista/blob/main/evaluation/calculate_score.py#L43C9-L43C67) that the choices in the problem dict are assigned the labels `A, B, C, ...` in order.

**Problem 1: The content of the answer choices in the problem dict do not match the content of the answer choices in the query prompt.**
In the problem dict, the answer choices contain "11:30" but in the query prompt, the answer choices contain "12:30"

**Problem 2: The ordering of the answer choices in the problem dict do not match the content of the answer choices in the query prompt.**
In the problem dict, the index of the correct answer, "4:30" is index 2, which corresponds to letter (C). However in the query prompt, the index of the correct answer, "4:30" is index 3, which corresponds to letter (D).

I am not sure what the rate of such errors is. I found this error by accident from looking at a random sample of 32 examples and checked the 16 multiple choice problems that were not yes/no problems, and found 1 such error out of the 16 that I sampled.

**Comment by lupantech** [comment]
Hi @mbchang,

Thank you so much for your careful review of our dataset. Based on your feedback, we re-examined the `query.json`. 

We noticed that the questions related to "What time does the clock show?" have the issues you reported. Only one question (i.e. PID: 272) in the testmini set exhibits both problems. 

Furthermore, fewer than 10 questions in the testmini set have inconsistent choice ordering. Considering that the final evaluation checks if the generated answers match the answer text, and not the option character, this issue does not affect the evaluation scores.

Thank you again for your valuable feedback. We have now fixed the issues in `query.json`.
