### ISSUE TITLE
How to apply for a leaderboard test

### ISSUE THREAD

**Issue by zRzRzRzRzRzRzR** [lupantech/MathVista#21]
In the code, I can complete the test of 1,000 local data on my own. I want to know, for the remaining 5,000 data, how should I submit to the leaderboard test to get the evaluation scores.

1. Where to upload the model ( or just submit the json file is ok,not model infer code)
2. Need Other resouce or just send a json file to email

Thanks

**Comment by lupantech** [comment]
I have updated the Readme file for more detailed instructions for contributing to the leaderboard. I highlight the updates below. Hope it is helpful to you!

The evaluation instructions are available at [🔮 Evaluations on MathVista](https://github.com/lupantech/MathVista?tab=readme-ov-file#-evaluations-on-mathvista) and [📝 Evaluation Scripts of Our Models](https://github.com/lupantech/MathVista?tab=readme-ov-file#-evaluation-scripts-of-our-models).

To submit your results to the leaderboard on the testmini subset, please send to [this email](mailto:lupantech@gmail.com) with your result json file and score json file, referring to the template files below:
- [output_testmini_template_for_leaderboard_submission.json](https://github.com/lupantech/MathVista/blob/main/results/leaderboad_submission_template/output_testmini_template_for_leaderboard_submission.json)
- [scores_testmini_template_for_leaderboard_submission.json](https://github.com/lupantech/MathVista/blob/main/results/leaderboad_submission_template/scores_testmini_template_for_leaderboard_submission.json)

To submit your results to the leaderboard on the test subset, please send to [this email](mailto:lupantech@gmail.com) with your result file (we will generate the score file for you), referring to the template file below:
- [output_test_template_for_leaderboard_submission.json](https://github.com/lupantech/MathVista/blob/main/results/leaderboad_submission_template/output_test_template_for_leaderboard_submission.json)
