### ISSUE TITLE
Syntax Correction Needed in README for Unzipping and Removing Command

### ISSUE THREAD

**Issue by Aboriginer** [lupantech/MathVista#24]
Hi Pan Lu,

Thanks for your excellent work!

There is a potential syntax error [here](https://github.com/lupantech/MathVista/blob/main/README.md#downloading-images-optional) regarding the unzip and remove command. It might be `unzip images.zip && rm images.zip`:)

**Comment by lupantech** [comment]
Thank you so much! I have fixed this issue.
