### ISSUE TITLE
Problem 479: Incorrect answer to a problem

### ISSUE THREAD

**Issue by mbchang** [lupantech/MathVista#7]
The correct answer to problem 479 is 56/22 = 2.5454545..., which should round to 2.55. However the ground truth answer is 2.54. [CoT GPT-4 (Caption+OCR)](https://github.com/lupantech/MathVista/blob/main/results/gpt4/output_gpt4_2shot_code_use_caption_ocr.json) answered "2.5454545454545454", but this is marked as incorrect given the [string-matching score calculation](https://github.com/lupantech/MathVista/blob/358f3f48c5c7776db755e20719af2dc0d1a733b9/evaluation/calculate_score.py#L62) employed by the paper.

```
>>> extraction = "2.5454545454545454"
>>> precision = 2
>>> str(round(float(extraction), precision))  # https://github.com/lupantech/MathVista/blob/358f3f48c5c7776db755e20719af2dc0d1a733b9/evaluation/calculate_score.py#L62
>>> 2.55
```

<img width="802" alt="image" src="https://github.com/lupantech/MathVista/assets/6439365/965caa25-2c89-4648-be29-dd0aa9f08991">

**Comment by lupantech** [comment]
Thank you for bringing up the issue in the evaluation of the answer for problem 479.

This inconsistency originates from the original source dataset, ChartQA. Indeed, creating a robust evaluation framework for mathematical reasoning poses significant challenges, highlighting the complexity of such tasks.

Considering the complexity of establishing a more robust evaluation, and to ensure consistent comparisons among current models, we maintain the existing evaluation framework for now. However, it is crucial to note that such discrepancies represent only a negligible proportion of the overall problems in the dataset, thus minimally impacting the overall model evaluation.

We are open to solve this challenge and aim to collaborate with the community to update the dataset in its next version and to propose more robust evaluation metrics.


Thanks again for your invaluable input!
