### ISSUE TITLE
Ordering of hint_text and other text when constructing the query

### ISSUE THREAD

**Issue by MikeWangWZHL** [lupantech/MathVista#8]
Thanks for open sourcing this great benchmark.

One quick question about the query generation.

In both the README and the output*.json files in the `results/`, I find that the Hint text should be appearing before the question, however, this line of code: https://github.com/lupantech/MathVista/blob/9da4bca0c27d7249bf461ea103645469bb4ff203/evaluation/build_query.py#L265 It seems the the hint text are putted afterward question_text. Is this a typo?

Thank you!

**Comment by lupantech** [comment]
Hi Mike,

Thank you so much for your kind words and acknowledgment!

In our implementations, for most models, such as large multimodal models and zero-shot language models, `hint_text` is placed before the other input elements.

For the few-shot language models, we made minor adjustments by placing `hint_text` at the very end of the input query. This is based on our empirical intuition that if the input query is very long, placing the hint text just before the end of the query might help generate answers in the expected formats as indicated by the hint text. But, we speculate the minor adjustments have a minor impact on the final performance.

Hope it could help clarify your questions. We also look forward to your experiments to further verify our intuitions.
