### ISSUE TITLE
GPT4V output file

### ISSUE THREAD

**Issue by TobiasLee** [lupantech/MathVista#9]
Thanks for your great work!

I'm currently working on computing multiple-choice accuracy scores for a subset of the testmini set. I've found the corresponding output file for output_llava_llama_2_13b.json under MathVista/results/llava/, but it seems to be missing in the gpt4v repository.

Could you please provide the missing multiple-choice accuracy output file for gpt4v for accurate comparisons?

Thanks in advance!

**Comment by TobiasLee** [comment]
@lupantech

**Comment by lupantech** [comment]
Hi @TobiasLee,

Thank you for your interest in MathVista! To assist you further with your request for the multiple-choice accuracy output file for gpt4v, could you please send the request to [this email](mailto:lupantech@gmail.com)? We appreciate your effort in making accurate comparisons.

Thank you!

Best regards,
Pan
